wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.7.10
      5: 0.10.31
      8:
      - 5
batch_size:
  desc: null
  value: 32
checkpoint_hist:
  desc: null
  value: 10
clip-mode:
  desc: null
  value: norm
clip_grad:
  desc: null
  value: 1
clip_mode:
  desc: null
  value: norm
config_path:
  desc: null
  value: pit_skin.yaml
cooldown_epochs:
  desc: null
  value: 0
csv_path:
  desc: null
  value: /home/ubuntu/workspace/vision.pjt/train.csv
data_dir:
  desc: null
  value: /home/ubuntu/workspace/vision.pjt/data/skin_images
decay_epochs:
  desc: null
  value: 0
decay_rate:
  desc: null
  value: 0.1
drop:
  desc: null
  value: 0.2
drop_block:
  desc: null
  value: null
drop_path:
  desc: null
  value: null
epochs:
  desc: null
  value: 20
eval_metric:
  desc: null
  value: loss
experiment:
  desc: null
  value: vision.pjt.skin
finetune:
  desc: null
  value: head
gp:
  desc: null
  value: null
img_size:
  desc: null
  value: 224
initial_checkpoint:
  desc: null
  value: ''
log_interval:
  desc: null
  value: 1
log_wandb:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0001
min_lr:
  desc: null
  value: 1.0e-05
model:
  desc: null
  value: pit_b_224
momentum:
  desc: null
  value: 0.9
momentums:
  desc: null
  value: 0.9
nprocs:
  desc: null
  value: 1
num_classes:
  desc: null
  value: 2
opt:
  desc: null
  value: adamw
opt_betas:
  desc: null
  value: null
opt_eps:
  desc: null
  value: 1.0e-08
output:
  desc: null
  value: /home/ubuntu/workspace/vision.pjt/output/model
patience_epochs:
  desc: null
  value: 0
pretrained:
  desc: null
  value: true
random_seed:
  desc: null
  value: 1234
save_best:
  desc: null
  value: loss
sched:
  desc: null
  value: cosine
valid_every_n_batch:
  desc: null
  value: 2
warmup_epochs:
  desc: null
  value: 2
warmup_lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.05
workers:
  desc: null
  value: 1
