# wandb.ai
log_wandb: True
experiment: "vision.pjt.lung"
img_size: 299
finetune: fc
# model
model: inception_v3
pretrained: True
num_classes: 3
drop: 0.2
# optimizer
opt: adamw
opt_eps: 1e-8
momentums: 0.9
weight_decay: 0.05
# learning rate
sched: cosine
lr: 1e-4
warmup_lr: 1e-5
warmup_epochs: 2
clip_grad: 1
clip-mode: norm
cooldown_epochs: 0
# training
batch_size: 64
epochs: 20
log_interval: 50
valid_every_n_batch: 1
# misc
output: "/home/ubuntu/workspace/vision.pjt/output/"
csv_path: "/home/ubuntu/workspace/vision.pjt/lung_5_local.csv"
data_dir: "/home/ubuntu/workspace/vision.pjt/data/preproc_images5"
