# wandb.ai
log_wandb: True
experiment: "vision.pjt.skin"
img_size: 224
finetune: head
# model
model: "pit_b_224"
pretrained: True
num_classes: 2
drop: 0.0
# optimizer
opt: adamw
opt_eps: 1e-8
momentums: 0.9
weight_decay: 0.05
# learning rate
sched: cosine
lr: 1e-2
warmup_lr: 1e-4
warmup_epochs: 2
# clip_grad: 1
# clip-mode: norm
cooldown_epochs: 0
# training
batch_size: 64
epochs: 20
log_interval: 1
valid_every_n_batch: 2
# misc
output: "/home/ubuntu/workspace/vision.pjt/output/"
csv_path: "/home/ubuntu/workspace/vision.pjt/train.csv"
data_dir: "/home/ubuntu/workspace/vision.pjt/data/skin_images"